image: elixir:1.11-alpine #update this when we switch Elixir version in Dockerfile

variables: 
  POSTGRES_DB: activity_pub_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  MIX_ENV: test
  HOSTNAME: localhost

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - deps
    - _build

stages:
  - test

before_script:
  - apk add --update --no-cache build-base git

unit-testing:
  stage: test
  services:
  - name: postgres:9.6.6
    command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix compile --force
    - mix ecto.create
    - mix ecto.migrate
    - mix coveralls --preload-modules
